// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQHMUhFSg_Kh2JjsfgUFNNlVFr64Rqvo',
    appId: '1:346611675786:web:31e344d573f8d7d16d7373',
    messagingSenderId: '346611675786',
    projectId: 'winston-salem-church-app',
    authDomain: 'winston-salem-church-app.firebaseapp.com',
    storageBucket: 'winston-salem-church-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlndfmsKn0IhW_jkPAi17fKy30R1ZmPo',
    appId: '1:346611675786:android:6f2f8009676ef7276d7373',
    messagingSenderId: '346611675786',
    projectId: 'winston-salem-church-app',
    storageBucket: 'winston-salem-church-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPD9KGzGq2UFYsJKMQTdoyGCQkKSXMFrg',
    appId: '1:346611675786:ios:dc7200064f7dd4316d7373',
    messagingSenderId: '346611675786',
    projectId: 'winston-salem-church-app',
    storageBucket: 'winston-salem-church-app.firebasestorage.app',
    iosClientId: '346611675786-ig28tjrqme5pnjre9k7stcme2c1djo6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPD9KGzGq2UFYsJKMQTdoyGCQkKSXMFrg',
    appId: '1:346611675786:ios:dc7200064f7dd4316d7373',
    messagingSenderId: '346611675786',
    projectId: 'winston-salem-church-app',
    storageBucket: 'winston-salem-church-app.firebasestorage.app',
    iosClientId: '346611675786-ig28tjrqme5pnjre9k7stcme2c1djo6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQHMUhFSg_Kh2JjsfgUFNNlVFr64Rqvo',
    appId: '1:346611675786:web:5a9ff85ab1fc87596d7373',
    messagingSenderId: '346611675786',
    projectId: 'winston-salem-church-app',
    authDomain: 'winston-salem-church-app.firebaseapp.com',
    storageBucket: 'winston-salem-church-app.firebasestorage.app',
  );
}
